-- LLAVES PRIMARIAS ----------------------------------------------------------------------------------------------------------
ALTER TABLE CARRITO ADD CONSTRAINT PK_CARRITO PRIMARY KEY (ID_CARRITO);
ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA);
ALTER TABLE DETALLE_ORDEN ADD CONSTRAINT PK_DETALLEORDEN PRIMARY KEY (ID_DETALLEORDEN);
ALTER TABLE H_ENTREGAS ADD CONSTRAINT PK_ENTREGAS PRIMARY KEY (ID_ENTREGAS);
ALTER TABLE H_ERRORES ADD CONSTRAINT PK_ERRORES PRIMARY KEY (ID_ERRORES);
ALTER TABLE INFO_PAGO ADD CONSTRAINT PK_INFOPAGO PRIMARY KEY (ID_INFOPAGO);
ALTER TABLE METODO_PAGO ADD CONSTRAINT PK_METODOPAGO PRIMARY KEY (ID_METODOPAGO);
ALTER TABLE ORDEN ADD CONSTRAINT PK_ORDEN PRIMARY KEY (ID_ORDEN);
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO);
ALTER TABLE PROVEEDOR ADD CONSTRAINT PK_PROVEEDOR PRIMARY KEY (ID_PROVEEDOR);
ALTER TABLE ROL ADD CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL);
ALTER TABLE SUCURSAL ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY (ID_SUCURSAL);
ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO);

-- LLAVES UNICAS -------------------------------------------------------------------------------------------------------------
ALTER TABLE CATEGORIA ADD CONSTRAINT UK_CATEGORIA UNIQUE (TIPO);
ALTER TABLE METODO_PAGO ADD CONSTRAINT UK_METODOPAGO UNIQUE (NOMBRE);
ALTER TABLE PROVEEDOR ADD CONSTRAINT UK_PROVEEDOR UNIQUE (CED_JURIDICA);
ALTER TABLE ROL ADD CONSTRAINT UK_ROL UNIQUE (TIPO);
ALTER TABLE USUARIO ADD CONSTRAINT UK_USUARIO UNIQUE (EMAIL);

-- LLAVES FORANEAS -----------------------------------------------------------------------------------------------------------
ALTER TABLE CARRITO ADD CONSTRAINT FK_CARRITO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);
ALTER TABLE CARRITO ADD CONSTRAINT FK_CARRITO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE DETALLE_ORDEN ADD CONSTRAINT FK_DETALLEORDEN_ORDEN FOREIGN KEY (ID_ORDEN) REFERENCES ORDEN (ID_ORDEN);

ALTER TABLE H_ENTREGAS ADD CONSTRAINT FK_ENTREGAS_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);
ALTER TABLE H_ENTREGAS ADD CONSTRAINT FK_ENTREGAS_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR);

ALTER TABLE H_ERRORES ADD CONSTRAINT FK_ERRORES_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE INFO_PAGO ADD CONSTRAINT FK_INFOPAGO_METODOPAGO FOREIGN KEY (ID_METODOPAGO) REFERENCES METODO_PAGO (ID_METODOPAGO);
ALTER TABLE INFO_PAGO ADD CONSTRAINT FK_INFOPAGO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE ORDEN ADD CONSTRAINT FK_ORDEN_INFOPAGO FOREIGN KEY (ID_INFOPAGO) REFERENCES INFO_PAGO (ID_INFOPAGO);
ALTER TABLE ORDEN ADD CONSTRAINT FK_ORDEN_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR);

ALTER TABLE PROVEEDOR ADD CONSTRAINT FK_PROVEEDOR_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL);

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL);

COMMIT;
